package org.kiuru.processor.quartus.generator

import java.io.{File, FileWriter}

object MifGenerator {

  def generate(depth: Int, width: Int, values: Seq[Int]): String = {
    val sb = new StringBuilder()
    
    sb.append("-- Generated by Quartus Transpiler\n")
    sb.append("-- Memory Initialization File (MIF) for Quartus II 13.1\n\n")
    
    sb.append("WIDTH = ").append(width).append(";\n")
    sb.append("DEPTH = ").append(depth).append(";\n\n")
    
    sb.append("ADDRESS_RADIX = HEX;\n")
    sb.append("DATA_RADIX = HEX;\n\n")
    
    sb.append("CONTENT BEGIN\n")
    
    // Validate values fit in width
    val mask = (1L << width) - 1
    val values32bit = values.map(v => (v.toLong & mask).toHexString.toUpperCase)
    
    for (i <- 0 until math.min(depth, values32bit.length)) {
      val address = i.toHexString.toUpperCase
      val value = values32bit(i)
      sb.append(f"  $address%08s : $value;\n")
    }
    
    sb.append("END;\n")
    
    sb.toString()
  }

  def saveToFile(mifContent: String, filePath: String): Unit = {
    val file = new File(filePath)
    file.getParentFile.mkdirs()
    val writer = new FileWriter(file)
    try {
      writer.write(mifContent)
    } finally {
      writer.close()
    }
  }
}
