package org.kiuru.processor.quartus.generator

import org.kiuru.processor.quartus.config.FPGAConfig
import java.io.{File, FileWriter}
import java.nio.file.{Files, Paths}

object QsfGenerator {

  def generate(config: FPGAConfig, projectName: String, verilogFile: String): String = {
    val sb = new StringBuilder()
    
    sb.append("# Project settings generated by Quartus Transpiler\n")
    sb.append("# Generated for Quartus II 13.1\n\n")
    
    // Device settings
    sb.append(s"set_global_assignment -name FAMILY \"${config.device.family}\"\n")
    sb.append(s"set_global_assignment -name DEVICE ${config.device.device}\n")
    config.device.partNumber.foreach { pn =>
      sb.append(s"set_global_assignment -name PART_NUMBER \"$pn\"\n")
    }
    
    // Top module and file settings
    sb.append(s"set_global_assignment -name TOP_LEVEL_ENTITY ${config.topModule}\n")
    sb.append(s"set_global_assignment -name VERILOG_FILE $verilogFile\n")
    sb.append("set_global_assignment -name SDC_FILE ${projectName}.sdc\n\n")
    
    // Optimization settings
    sb.append(s"set_global_assignment -name OPTIMIZATION_TECHNIQUE ${config.optimizationTechnique}\n")
    
    // Timing analysis
    if (config.device.timingAnalysis) {
      sb.append("set_global_assignment -name TIMEQUEST_MULTICORNER_ANALYSIS ON\n")
      sb.append("set_global_assignment -name TIMEQUEST_DO_CCPP_REMOVAL ON\n")
    }
    
    // Power estimation
    if (config.powerEstimation) {
      sb.append("set_global_assignment -name POWER_PRESET_COOLING_SOLUTION \"23 MM HEAT SINK WITH 200 LFPM AIRFLOW\"\n")
      sb.append("set_global_assignment -name POWER_BOARD_THERMAL_MODEL \"NONE (CONSERVATIVE)\"\n")
    }
    
    // Synthesis settings
    sb.append("set_global_assignment -name SYNTH_TIMING_DRIVEN_SYNTHESIS ON\n")
    sb.append("set_global_assignment -name USE_CONFIGURATION_DEVICE OFF\n")
    sb.append("set_global_assignment -name GENERATE_TTF_FILE ON\n")
    
    sb.append("\n# Pin assignments\n")
    
    // Pin assignments
    config.pins.foreach { pin =>
      sb.append(s"set_instance_assignment -name IO_STANDARD \"${pin.ioStandard.getOrElse("3.3-V LVCMOS")}\" -to ${pin.name}\n")
      sb.append(s"set_instance_assignment -name CURRENT_STRENGTH_NEW \"${pin.currentStrength.getOrElse("8MA")}\" -to ${pin.name}\n")
      if (pin.pullUp.getOrElse(false)) {
        sb.append(s"set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to ${pin.name}\n")
      }
      sb.append(s"set_instance_assignment -name SLEW_RATE 1 -to ${pin.name}\n")
    }
    
    sb.append("\n# Misc settings\n")
    sb.append("set_global_assignment -name ENABLE_SIGNALTAP OFF\n")
    sb.append("set_global_assignment -name VERILOG_INPUT_VERSION SYSTEMVERILOG_2009\n")
    
    // Additional misc files
    config.miscFiles.foreach { file =>
      sb.append(s"set_global_assignment -name MISC_FILE \"$file\"\n")
    }
    
    sb.toString()
  }

  def saveToFile(qsfContent: String, filePath: String): Unit = {
    val file = new File(filePath)
    file.getParentFile.mkdirs()
    val writer = new FileWriter(file)
    try {
      writer.write(qsfContent)
    } finally {
      writer.close()
    }
  }
}
