package org.kiuru.processor.quartus.generator

import org.kiuru.processor.quartus.config.FPGAConfig
import java.io.{File, FileWriter}

object SdcGenerator {

  def generate(config: FPGAConfig, clockNames: Seq[String] = Seq("clk")): String = {
    val sb = new StringBuilder()
    
    sb.append("# Generated by Quartus Transpiler\n")
    sb.append("# Synopsys Design Constraints (SDC) file for Quartus II 13.1\n\n")
    
    // Clock constraints
    val period = 1000.0 / config.device.clockFreqMHz
    val halfPeriod = period / 2.0
    
    for (clockName <- clockNames) {
      sb.append(s"create_clock -name $clockName -period $period -waveform {0.0 $halfPeriod} [get_ports $clockName]\n")
    }
    
    sb.append("\n# Input delays\n")
    
    // Input delay constraints for non-clock pins
    val inputPins = config.pins.filter(p => clockNames.forall(c => c != p.name))
    if (inputPins.nonEmpty) {
      val inputPinNames = inputPins.map(_.name).mkString(" ")
      sb.append(s"set_input_delay -clock clk -max 3.0 [get_ports {$inputPinNames}]\n")
      sb.append(s"set_input_delay -clock clk -min 0.0 [get_ports {$inputPinNames}]\n")
    }
    
    sb.append("\n# Output delays\n")
    sb.append("set_output_delay -clock clk -max 3.0 [get_ports {*}]\n")
    sb.append("set_output_delay -clock clk -min 0.0 [get_ports {*}]\n")
    
    sb.append("\n# Multicycle constraints (optional)\n")
    sb.append("# set_multicycle_path -setup -from {*} -to {*} 2\n")
    sb.append("# set_multicycle_path -hold -from {*} -to {*} 1\n")
    
    sb.toString()
  }

  def saveToFile(sdcContent: String, filePath: String): Unit = {
    val file = new File(filePath)
    file.getParentFile.mkdirs()
    val writer = new FileWriter(file)
    try {
      writer.write(sdcContent)
    } finally {
      writer.close()
    }
  }
}
