package org.kiuru.processor.quartus.generator

import java.io.{File, FileWriter}

object ShellScriptGen {

  def generate(projectName: String, verilogFile: String): String = {
    val sb = new StringBuilder()
    
    sb.append("# Generated by Quartus Transpiler\n")
    sb.append("# TCL script for Quartus II 13.1 shell (quartus_sh)\n")
    sb.append("# Usage: quartus_sh -t build.tcl\n\n")
    
    sb.append("# Load Quartus environment\n")
    sb.append("load_package flow\n")
    sb.append("load_package report\n\n")
    
    sb.append("# Create new project\n")
    sb.append(s"project_new -name $projectName -revision $projectName -overwrite\n\n")
    
    sb.append("# Set device and pin assignments\n")
    sb.append(s"set_global_assignment -name TOP_LEVEL_ENTITY top_module\n")
    sb.append(s"set_global_assignment -name VERILOG_FILE $verilogFile\n\n")
    
    sb.append("# Run synthesis, place and route\n")
    sb.append("execute_module -tool map\n")
    sb.append("execute_module -tool fit\n")
    sb.append("execute_module -tool sta\n")
    sb.append("execute_module -tool eda\n\n")
    
    sb.append("# Generate timing report\n")
    sb.append("execute_module -tool sta\n\n")
    
    sb.append("# Generate programming file\n")
    sb.append("execute_module -tool asm\n\n")
    
    sb.append("# Close project\n")
    sb.append("project_close\n")
    
    sb.toString()
  }

  def saveToFile(tclContent: String, filePath: String): Unit = {
    val file = new File(filePath)
    file.getParentFile.mkdirs()
    val writer = new FileWriter(file)
    try {
      writer.write(tclContent)
    } finally {
      writer.close()
    }
  }
}
