package org.kiuru.processor.quartus.transform

import org.kiuru.processor.quartus.ast._
import org.kiuru.processor.quartus.parser.VerilogParser

/**
 * Утилита для трансформации Verilog кода в Quartus II 13.1 совместимый формат.
 * 
 * Пример использования:
 * {{{
 *   val verilogCode = """
 *     module 1 (
 *       input clk,
 *       output wire signed [31:0] count
 *     );
 *       wire signed result;
 *       always @(posedge clk) begin
 *         result <= count + 1;
 *       end
 *     endmodule
 *   """
 *   
 *   val quartusVerilog = VerilogToQuartus.transform(verilogCode)
 *   println(quartusVerilog)
 * }}}
 */
object VerilogToQuartus {

  /**
   * Трансформировать Verilog код в Quartus II 13.1 совместимый формат
   *
   * @param verilogCode исходный Verilog код
   * @param options параметры трансформации
   * @return трансформированный Verilog код
   */
  def transform(verilogCode: String, options: TransformOptions = TransformOptions()): String = {
    try {
      val parser = new VerilogParser(verilogCode)
      val module = parser.parseModule()
      
      val transformer = new QuartusTransformer(options)
      val transformedModule = transformer.transformModule(module)
      
      val verilogOutput = moduleToVerilog(transformedModule, options)
      verilogOutput
    } catch {
      case e: Exception =>
        s"// ERROR: ${e.getMessage}\n$verilogCode"
    }
  }

  /**
   * Трансформировать несколько модулей
   *
   * @param modules список модулей для трансформации
   * @param options параметры трансформации
   * @return трансформированный список модулей
   */
  def transformModules(modules: Seq[Module], options: TransformOptions = TransformOptions()): Seq[Module] = {
    val transformer = new QuartusTransformer(options)
    transformer.transformModules(modules)
  }

  /**
   * Конвертировать Module AST обратно в Verilog код
   *
   * @param module модуль для конвертации
   * @param options параметры форматирования
   * @return Verilog текст
   */
  private def moduleToVerilog(module: Module, options: TransformOptions): String = {
    val sb = StringBuilder.newBuilder

    // Header комментарий
    if (options.addFixMarkers) {
      sb.append("// ## QUARTUS II 13.1 Compatible Verilog\n")
      sb.append("// ## Auto-generated by QuartusTransformer\n\n")
    }

    // Module declaration
    sb.append(s"module ${module.name}")

    if (module.ports.nonEmpty) {
      sb.append(" (\n")
      for ((port, idx) <- module.ports.zipWithIndex) {
        sb.append(s"  ${port.direction} ${port.widthString} ${port.name}")
        if (idx < module.ports.length - 1) sb.append(",")
        sb.append("\n")
      }
      sb.append(");\n\n")
    } else {
      sb.append(";\n\n")
    }

    // Module items
    for (item <- module.items) {
      item match {
        case wire: Wire =>
          sb.append(s"  wire ${wire.widthString} ${wire.name};\n")

        case reg: Reg =>
          sb.append(s"  reg ${reg.widthString} ${reg.name};\n")

        case param: Parameter =>
          val value = param.defaultValue.map(v => s" = $v").getOrElse("")
          sb.append(s"  parameter ${param.valueType} ${param.name}$value;\n")

        case lp: Localparam =>
          sb.append(s"  localparam ${lp.name} = ${lp.value};\n")

        case assign: Assign =>
          sb.append(s"  assign ${assign.lhs} = ${assign.rhs};\n")

        case always: AlwaysBlock =>
          sb.append(s"  always ${always.trigger} begin\n")
          for (stmt <- always.statements) {
            sb.append(s"    $stmt\n")
          }
          sb.append("  end\n")

        case instance: ModuleInstance =>
          sb.append(s"  ${instance.moduleName} ${instance.instanceName} (\n")
          val connections = instance.connections
            .map { case (port, signal) => s"    .$port($signal)" }
            .mkString(",\n")
          sb.append(connections)
          sb.append("\n  );\n")

        case _ =>
          sb.append(s"  // Unknown item: $item\n")
      }
    }

    sb.append("\nendmodule\n")
    sb.toString
  }

  /**
   * Получить summary трансформации
   *
   * @param options параметры трансформации
   * @return текстовое описание
   */
  def getTransformSummary(options: TransformOptions = TransformOptions()): String = {
    new QuartusTransformer(options).getTransformSummary
  }
}
